# Generated by Django 5.2.3 on 2025-06-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='B',
            new_name='Bb',
        ),
    ]
